services:
  model-redis:
    image: origin-hub-ai-registry.cn-shanghai.cr.aliyuncs.com/dataflow/redis:8
    container_name: model-redis
    restart: unless-stopped
    hostname: model-redis
    networks:
      - model-network
    volumes:
      - ./volumes/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  model_proxy:
    image: origin-hub-ai-registry.cn-shanghai.cr.aliyuncs.com/dataflow/model_proxy:v1.0.0
    ports:
      - 8000:8000
    container_name: model_proxy
    hostname: model_proxy
    environment:
        REDIS_URL: redis://model-redis:6379
    env_file:
      - .env
    depends_on:
      model-redis:
        condition: service_healthy
    networks:
      - model-network
    restart: unless-stopped

networks:
  model-network:
    name: model-network
    driver: bridge
